name: JawaToolBox
main: net.jawasystems.jawatoolbox.JawaToolBox
version: ${pom.version}
description: "A toolbox with general server customization options such as sleep control, motd, and maintenance mode."
author: Jawamaster (Arthur Bulin)
website: jawasystems.net
api-version: 1.20
commands:
  mmadd:
    description: Used to add a user to the maintenance mode whitelist
    usage: /mmadd <uuid|playername>
    permission: jawatoolbox.mm.add
  mmtoggle:
    description: Used to toggle active state of maintenance mode
    usage: /mmtoggle
    permission: jawatoolbox.mm.toggle
  mmremove:
    description: Used to remove a user from the maintenance mode list
    usage: /mmremove <uuid|playername>
    permission: jawatoolbox.mm.remove
  mmstatus:
    description: Used to see the maintenance status of the server
    usage: /mmstatus
    permission: jawatoolbox.mm.status
  motd:
    description: 'Used to interact with MOTD settings'
    usage: '/motd [help,edit,rem,add] <type> [index] [message]'
    permission: jawatoolbox.motd
  jawatoolbox:
    description: 'Used to read the change log and description'
    usage: '/jawatoolbox [version]'
    
permissions:
  jawatoolbox.motd:
      description: Allows basic use of the motd command
      default: true
  jawatoolbox.mm.*:
      description: Maintenance mode control
      default: op